# CALIDAD DE DATOS PREDICTION

**IMPORTANTE**: Nosotros ya hemos hecho una fase de calidad de datos satisfactoria pero vamos a hacer algunas comprobaciones sobre atipícos por si pudiera aportarnos algo de mejora en el dataset

## IMPORTAR PAQUETES

In [22]:
import numpy as np
import pandas as pd
from janitor import clean_names

#Automcompletar rápido
%config IPCompleter.greedy=True

pd.options.display.float_format = '{:15.2f}'.format

## IMPORTAR LOS DATOS

Sustituir la ruta del proyecto.

In [23]:
ruta_proyecto = 'C:/Users/Oscar/OneDrive - FM4/Escritorio/Python Data Mastery/EstructuraDirectorio/03_MACHINE_LEARNING/08_CASOS/007_AIRBNB'

Sustituir el nombre_fichero_datos.

In [24]:
nombre_fichero_datos = 'trabajo.csv'

Cargar los datos.

In [25]:
ruta_completa = ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_fichero_datos

df = pd.read_csv(ruta_completa,index_col=0).set_index('id')
df

,index,name,host_response_time,host_is_superhost,host_verifications,host_has_profile_pic,host_identity_verified,property_type,room_type,amenities,...,calculated_host_listings_count_shared_rooms,reviews_per_month,precio_m2,bedrooms_disc,accommodates_disc,beds_disc,number_of_reviews_disc,m2,pdi_sol,pisos_rentables
id,,,,,,,,,,,,,,,,,,,,,
21853,0,Bright and airy room,no response,f,"['email', 'phone']",t,t,Private room in rental unit,Private room,"[""First aid kit"", ""Wifi"", ""Kitchen"", ""Essentia...",...,0,0.27,2772,01_Una,0-3,1,5-71,50,3.52,1
30959,2,Beautiful loft in Madrid Center,no response,f,"['email', 'phone']",t,f,Entire loft,Entire home/apt,"[""Breakfast"", ""Heating"", ""Wifi"", ""Smoking allo...",...,0,0.07,6170,01_Una,0-3,1,1-4,50,0.50,1
40916,3,Holiday Apartment Madrid Center,no response,f,"['email', 'phone']",t,f,Entire rental unit,Entire home/apt,"[""Heating"", ""Wifi"", ""Pets allowed"", ""Kitchen"",...",...,0,0.29,6170,01_Una,0-3,3,5-71,50,0.67,1
62423,4,MAGIC ARTISTIC HOUSE IN THE CENTER OF MADRID,within an hour,f,"['email', 'phone']",t,t,Private room in rental unit,Private room,"[""Books and reading material"", ""First aid kit""...",...,0,2.73,6170,01_Una,4,3,71-1136,50,0.62,0
70059,5,Tu hogar en centro de Madrid.,no response,f,"['email', 'phone']",t,t,Entire rental unit,Entire home/apt,"[""Wifi"", ""Window AC unit"", ""Kitchen"", ""Essenti...",...,0,0.36,6170,01_Una,0-3,1,5-71,50,0.99,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1308797105765566482,25907,Elegancia y Comodidad en el Corazón de Madrid,within a few hours,f,"['email', 'phone']",t,t,Entire rental unit,Entire home/apt,"[""Wifi"", ""Kitchen"", ""Hot water"", ""Microwave"", ...",...,0,0.00,4876,01_Una,0-3,1,1-4,50,1.79,0
1308811268356474614,25908,Habitación tranquila,within an hour,f,['phone'],t,t,Private room in rental unit,Private room,"[""Wifi"", ""TV""]",...,0,0.00,3676,01_Una,0-3,1,1-4,50,4.44,0
1308816654087147793,25909,Vive Madrid Río con Confort y Estilo,within a few hours,f,"['email', 'phone']",t,t,Entire rental unit,Entire home/apt,"[""Wifi"", ""Kitchen"", ""Hot water"", ""Microwave"", ...",...,0,0.00,2772,01_Una,4,3,1-4,50,1.79,0
1308818613904246041,25910,Alquilo habitación por 15 días.,no response,f,"['email', 'phone']",t,t,Private room in rental unit,Private room,"[""Wifi"", ""Kitchen"", ""TV""]",...,0,0.00,6170,01_Una,0-3,1,1-4,50,0.61,0
1308864880309321118,25912,Precioso y Moderno en el Centro,within an hour,f,"['email', 'phone', 'work_email']",t,t,Entire rental unit,Entire home/apt,"[""Paid parking on premises"", ""Exercise equipme...",...,0,0.00,4850,01_Una,0-3,1,1-4,50,2.96,1

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18139 entries, 21853 to 1308864880309321118
Data columns (total 58 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   index                                         18139 non-null  int64
 1   name                                          18139 non-null  object
 2   host_response_time                            18139 non-null  object
 3   host_is_superhost                             18139 non-null  object
 4   host_verifications                            18139 non-null  object
 5   host_has_profile_pic                          18139 non-null  object
 6   host_identity_verified                        18139 non-null  object
 7   property_type                                 18139 non-null  object
 8   room_type                                     18139 non-null  object
 9   amenities                                     18139 non-null  object
 10  has_availability                              18139 non-null  object
 11  license                                       18139 non-null  object
 12  instant_bookable                              18139 non-null  object
 13  neighbourhood_group                           18139 non-null  object
 14  host_id                                       18139 non-null  int64
 15  host_since                                    18139 non-null  object
 16  host_response_rate                            18139 non-null  float64
 17  host_acceptance_rate                          18139 non-null  float64
 18  host_listings_count                           18139 non-null  float64
 19  host_total_listings_count                     18139 non-null  float64
 20  latitude                                      18139 non-null  float64
 21  longitude                                     18139 non-null  float64
 22  accommodates                                  18139 non-null  int64
 23  bathrooms                                     18139 non-null  float64
 24  bedrooms                                      18139 non-null  float64
 25  beds                                          18139 non-null  float64
 26  price                                         18139 non-null  int64
 27  minimum_nights                                18139 non-null  int64
 28  maximum_nights                                18139 non-null  int64
 29  availability_30                               18139 non-null  int64
 30  availability_60                               18139 non-null  int64
 31  availability_90                               18139 non-null  int64
 32  availability_365                              18139 non-null  int64
 33  number_of_reviews                             18139 non-null  int64
 34  number_of_reviews_ltm                         18139 non-null  int64
 35  number_of_reviews_l30d                        18139 non-null  int64
 36  first_review                                  18139 non-null  object
 37  last_review                                   18139 non-null  object
 38  review_scores_rating                          18139 non-null  float64
 39  review_scores_accuracy                        18139 non-null  float64
 40  review_scores_cleanliness                     18139 non-null  float64
 41  review_scores_checkin                         18139 non-null  float64
 42  review_scores_communication                   18139 non-null  float64
 43  review_scores_location                        18139 non-null  float64
 44  review_scores_value                           18139 non-null  float64
 45  calculated_host_listings_count                18139 non-null  int64
 46  calculated_host_listings_count_entire_homes   18139 non-null  int64
 47  calculated_host_listings_count_private_rooms  18139 non-null  int64
 48  calculated_host_listings_count_shared_rooms   18139 non-null  int64
 49  reviews_per_month                             18139 non-null  float64
 50  precio_m2                                     18139 non-null  int64
 51  bedrooms_disc                                 18139 non-null  object
 52  accommodates_disc                             18139 non-null  object
 53  beds_disc                                     18139 non-null  object
 54  number_of_reviews_disc                        18139 non-null  object
 55  m2                                            18139 non-null  int64
 56  pdi_sol                                       18139 non-null  float64
 57  pisos_rentables                               18139 non-null  int64
dtypes: float64(18), int64(20), object(20)
memory usage: 8.2+ MB

## VALORES ÚNICOS

### Identificación

In [27]:
df.nunique().sort_values()

pisos_rentables                                     2
host_is_superhost                                   2
instant_bookable                                    2
host_has_profile_pic                                2
host_identity_verified                              2
license                                             2
has_availability                                    2
accommodates_disc                                   3
beds_disc                                           3
room_type                                           3
number_of_reviews_disc                              3
bedrooms_disc                                       5
host_response_time                                  5
m2                                                  6
host_verifications                                  7
bedrooms                                           13
calculated_host_listings_count_shared_rooms        13
accommodates                                       16
number_of_reviews_l30d                             18
bathrooms                                          18
beds                                               18
precio_m2                                          21
neighbourhood_group                                21
calculated_host_listings_count_private_rooms       30
availability_30                                    31
property_type                                      56
availability_60                                    61
calculated_host_listings_count_entire_homes        68
calculated_host_listings_count                     71
minimum_nights                                     84
host_response_rate                                 85
availability_90                                    91
host_acceptance_rate                              100
host_listings_count                               110
review_scores_checkin                             134
host_total_listings_count                         137
review_scores_communication                       140
review_scores_accuracy                            145
review_scores_location                            150
number_of_reviews_ltm                             151
review_scores_cleanliness                         155
review_scores_rating                              158
maximum_nights                                    165
review_scores_value                               167
availability_365                                  366
number_of_reviews                                 543
price                                             552
reviews_per_month                                 912
last_review                                      2600
first_review                                     3591
host_since                                       3856
host_id                                          9369
longitude                                       11956
latitude                                        12398
amenities                                       15950
name                                            17220
pdi_sol                                         17418
index                                           18139
dtype: int64

## SEPARAR NUMÉRICAS Y CATEGÓRICAS

### Categóricas

In [28]:
cat = df.select_dtypes(exclude = 'number').copy()

### Numéricas

In [29]:
num = df.select_dtypes(include='number').copy()

## GESTIÓN DE CATEGÓRICAS

### Nulos

#### Identificación

In [30]:
#Es importante investigar bien los datos que aparecen como nulos porque puede que estén mal identificados como nulos
cat.isna().sum().sort_values(ascending = False)

name                      0
host_response_time        0
beds_disc                 0
accommodates_disc         0
bedrooms_disc             0
last_review               0
first_review              0
host_since                0
neighbourhood_group       0
instant_bookable          0
license                   0
has_availability          0
amenities                 0
room_type                 0
property_type             0
host_identity_verified    0
host_has_profile_pic      0
host_verifications        0
host_is_superhost         0
number_of_reviews_disc    0
dtype: int64

### Atípicos

#### Categorías poco frecuentes

##### Identificación

In [31]:
for variable in cat:
    print(variable + '\n')
    print(cat[variable].value_counts(dropna = False))
    print('\n\n')

name

name
Vibrating Hostel in Tetuán close to S. Bernabeu        25
Habitación con baño privado                            24
Habitación en Madrid                                   20
H Individual In Reformed Residence has wifi & cent     17
Habitación privada                                     15
                                                       ..
Captivating Apartment in Madrid near El Retiro Park     1
Bright apartment Oshun in Madrid Norte E                1
Arenal Suites Gran Vía Estudio (7)                      1
Arenal Suites Puerta del Sol 1 Habitaciones (1-4)       1
Precioso y Moderno en el Centro                         1
Name: count, Length: 17220, dtype: int64



host_response_time

host_response_time
within an hour        10742
no response            3482
within a few hours     1959
within a day           1173
a few days or more      783
Name: count, dtype: int64



host_is_superhost

host_is_superhost
f    13370
t     4769
Name: count, dtype: int64



host_verifications

host_verifications
['email', 'phone']                  13915
['phone']                            1875
['email', 'phone', 'work_email']     1869
['phone', 'work_email']               416
['email']                              41
['No']                                 20
['email', 'work_email']                 3
Name: count, dtype: int64



host_has_profile_pic

host_has_profile_pic
t    17551
f      588
Name: count, dtype: int64



host_identity_verified

host_identity_verified
t    16207
f     1932
Name: count, dtype: int64



property_type

property_type
Entire rental unit                    10807
Private room in rental unit            4511
Private room in home                    573
Entire condo                            438
Entire loft                             389
Entire home                             244
Entire serviced apartment               236
Private room in condo                   224
Private room in casa particular         118
Private room in bed and breakfast        86
Shared room in rental unit               62
Shared room in bed and breakfast         43
Private room in guesthouse               36
Shared room in guesthouse                31
Private room in guest suite              29
Private room                             28
Private room in loft                     24
Private room in serviced apartment       24
Private room in townhouse                22
Private room in chalet                   22
Entire vacation home                     18
Entire guest suite                       17
Tiny home                                14
Entire guesthouse                        14
Camper/RV                                12
Entire place                             12
Shared room in home                      12
Casa particular                          10
Entire townhouse                         10
Private room in villa                     8
Private room in tiny home                 7
Private room in floor                     6
Private room in vacation home             5
Floor                                     5
Shared room in loft                       4
Private room in dome                      4
Entire chalet                             4
Private room in cave                      3
Entire villa                              3
Shared room in condo                      3
Private room in earthen home              3
Entire cabin                              2
Shared room                               2
Entire home/apt                           2
Shared room in dome                       1
Private room in cottage                   1
Private room in barn                      1
Private room in pension                   1
Private room in bungalow                  1
Private room in minsu                     1
Private room in ryokan                    1
Private room in tent                      1
Hut                                       1
Shared room in casa particular            1
Entire bungalow                           1
Shared room in tiny home                  1
Name: count, dtype: int64



room_type

room_type
Entire home/apt    12239
Private room        5740
Shared room          160
Name: count, dtype: int64



amenities

amenities
["Wifi", "Kitchen", "TV", "Washer", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           90
["Wifi", "Kitchen", "TV", "Washer", "Dedicated workspace", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    70
["Hangers", "Clothing storage", "Heating", "Wifi", "Bed linens", "Kitchen", "TV", "Essentials", "Washer", "Dedicated workspace", "Cooking basics", "Host greets you", "Hot water"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                64
["Wifi", "Kitchen", "Essentials", "Stove", "Smart lock", "Hot water", "Iron", "Microwave", "Heating", "Toaster", "Hot water kettle", "TV", "Washer", "Elevator", "Shampoo", "Hair dryer", "Bed linens", "Air conditioning", "Freezer", "Coffee maker", "Dishwasher", "Oven", "Self check-in", "Refrigerator", "Dishes and silverware"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            54
["Wifi", "Kitchen", "TV", "Washer"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               50
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ..
["Private living room", "First aid kit", "Heating", "Wifi", "Smoking allowed", "Kitchen", "TV", "Essentials", "Washer", "Carbon monoxide alarm", "Iron", "Shampoo"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
["First aid kit", "Wifi", "Window AC unit", "Kitchen", "Essentials", "Stove", "Smart lock", "Hot water", "Iron", "Microwave", "Hangers", "Extra pillows and blankets", "Dining table", "Free washer \u2013 In unit", "Toaster", "Hot water kettle", "Carbon monoxide alarm", "Fire extinguisher", "Paid parking garage off premises", "HDTV", "Smoke alarm", "Radiant heating", "Hair dryer", "Drying rack for clothing", "Dishwasher", "Cleaning products", "Coffee maker: Nespresso", "Oven", "Self check-in", "Cooking basics", "Wine glasses", "Refrigerator", "Dishes and silverware"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
["Breakfast", "Wifi", "Kitchen", "Essentials", "Hot water", "Iron", "Paid parking off premises", "Microwave", "Hangers", "Portable fans", "Heating", "Private patio or balcony", "TV", "Washer", "Fire extinguisher", "Shampoo", "Long term stays allowed", "Hair dryer", "Coffee maker", "Dishwasher", "Cleaning products", "Oven", "Children\u2019s dinnerware", "Cooking basics", "Refrigerator", "Dishes and silverware"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
["Ethernet connection", "Wifi", "Central air conditioning", "Window AC unit", "Clothing storage: closet", "Kitchen", "Essentials", "Hot water", "Iron", "Luggage dropoff allowed", "Microwave", "Hangers", "Extra pillows and blankets", "Portable fans", "Dining table", "Free washer \u2013 In unit", "Pack \u2019n play/Travel crib", "Toaster", "Baking sheet", "Shower gel", "Hot water kettle", "Paid parking lot off premises", "High chair", "Indesit stainless steel oven", "Shampoo", "Wine glasses", "Radiant heating", "Long term stays allowed", "Body soap", "Hair dryer", "Bed linens", "Indesit induction stove", "50 inch HDTV with premium cable, standard cable", "Host greets you", "Freezer", "Laundromat nearby", "Drying rack for clothing", "Conditioner", "Window guards", "Dishwasher", "Private entrance", "Cleaning products", "Indesit refrigerator", "Coffee maker: Nespresso", "Paid parking garage on premises \u2013 1 space", "Children\u2019s dinnerware", "Cooking basics", "Room-darkening shades", "Dishes and silverware", "Crib", "Single level home"]     1
["Paid parking on premises", "Exercise equipment", "Smoke alarm", "Pool", "Exterior security cameras on property", "Wifi", "Smoking allowed", "Kitchen", "TV", "Washer", "Carbon monoxide alarm", "Fire extinguisher", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Name: count, Length: 15950, dtype: int64



has_availability

has_availability
yes    17082
no      1057
Name: count, dtype: int64



license

license
no     16321
yes     1818
Name: count, dtype: int64



instant_bookable

instant_bookable
f    10819
t     7320
Name: count, dtype: int64



neighbourhood_group

neighbourhood_group
Centro                7389
Salamanca             1224
Chamberí              1178
Tetuán                1131
Arganzuela             963
Carabanchel            699
Ciudad Lineal          674
Retiro                 674
Chamartín              609
Puente de Vallecas     560
Latina                 501
Moncloa                474
Usera                  421
San Blas               420
Hortaleza              342
Fuencarral             272
Villaverde             192
Moratalaz              137
Barajas                126
Villa de Vallecas       95
Vicálvaro               58
Name: count, dtype: int64



host_since

host_since
2020-11-30    241
2019-09-03    223
2021-12-30    214
2020-05-15    214
2023-06-07    178
             ...
2018-02-13      1
2018-11-06      1
2019-01-26      1
2015-09-26      1
2024-04-05      1
Name: count, Length: 3856, dtype: int64



first_review

first_review
2021-12-30    189
2020-05-15    151
2023-06-07     85
2022-07-28     85
2024-05-08     75
             ...
2019-01-06      1
2017-01-25      1
2019-01-07      1
2018-11-15      1
2015-03-07      1
Name: count, Length: 3591, dtype: int64



last_review

last_review
2024-12-08    862
2024-11-24    601
2024-12-01    555
2024-12-09    540
2024-11-25    377
             ...
2023-03-07      1
2019-01-27      1
2021-06-18      1
2021-10-07      1
2016-08-21      1
Name: count, Length: 2600, dtype: int64



bedrooms_disc

bedrooms_disc
01_Una             9915
02_Dos             3712
00_Estudio         2722
03_Tres            1287
04_Cuatro o mas     503
Name: count, dtype: int64



accommodates_disc

accommodates_disc
0-3     10775
4        4415
4-16     2949
Name: count, dtype: int64



beds_disc

beds_disc
1       9148
3       7351
3-19    1640
Name: count, dtype: int64



number_of_reviews_disc

number_of_reviews_disc
1-4        9166
5-71       5337
71-1136    3636
Name: count, dtype: int64

##### Función para agrupar categorías raras en 'OTROS'

In [32]:
def agrupar_cat_raras(variable, criterio = 0.05):
    #Calcula las frecuencias
    frecuencias = variable.value_counts(normalize=True)
    #Identifica las que están por debajo del criterio
    temp = [cada for cada in frecuencias.loc[frecuencias < criterio].index.values]
    #Las recodifica en 'OTROS'
    temp2 = np.where(variable.isin(temp),'OTROS',variable)
    #Devuelve el resultado
    return(temp2)

##### Variables a imputar

In [33]:
var_imputar_cat_raras = ['property_type']

##### Aplicar

In [34]:
for variable in var_imputar_cat_raras:
    cat[variable] = agrupar_cat_raras(cat[variable],criterio = 0.02)

In [35]:
cat['host_verifications'] = np.where(cat.host_verifications == "['email', 'work_email']", "['email']", cat.host_verifications)

Comprobamos los cambios aplicados

In [36]:
for variable in cat:
    print(variable + '\n')
    print(cat[variable].value_counts(dropna = False))
    print('\n\n')

name

name
Vibrating Hostel in Tetuán close to S. Bernabeu        25
Habitación con baño privado                            24
Habitación en Madrid                                   20
H Individual In Reformed Residence has wifi & cent     17
Habitación privada                                     15
                                                       ..
Captivating Apartment in Madrid near El Retiro Park     1
Bright apartment Oshun in Madrid Norte E                1
Arenal Suites Gran Vía Estudio (7)                      1
Arenal Suites Puerta del Sol 1 Habitaciones (1-4)       1
Precioso y Moderno en el Centro                         1
Name: count, Length: 17220, dtype: int64



host_response_time

host_response_time
within an hour        10742
no response            3482
within a few hours     1959
within a day           1173
a few days or more      783
Name: count, dtype: int64



host_is_superhost

host_is_superhost
f    13370
t     4769
Name: count, dtype: int64



host_verifications

host_verifications
['email', 'phone']                  13915
['phone']                            1875
['email', 'phone', 'work_email']     1869
['phone', 'work_email']               416
['email']                              44
['No']                                 20
Name: count, dtype: int64



host_has_profile_pic

host_has_profile_pic
t    17551
f      588
Name: count, dtype: int64



host_identity_verified

host_identity_verified
t    16207
f     1932
Name: count, dtype: int64



property_type

property_type
Entire rental unit             10807
Private room in rental unit     4511
OTROS                           1421
Private room in home             573
Entire condo                     438
Entire loft                      389
Name: count, dtype: int64



room_type

room_type
Entire home/apt    12239
Private room        5740
Shared room          160
Name: count, dtype: int64



amenities

amenities
["Wifi", "Kitchen", "TV", "Washer", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           90
["Wifi", "Kitchen", "TV", "Washer", "Dedicated workspace", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    70
["Hangers", "Clothing storage", "Heating", "Wifi", "Bed linens", "Kitchen", "TV", "Essentials", "Washer", "Dedicated workspace", "Cooking basics", "Host greets you", "Hot water"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                64
["Wifi", "Kitchen", "Essentials", "Stove", "Smart lock", "Hot water", "Iron", "Microwave", "Heating", "Toaster", "Hot water kettle", "TV", "Washer", "Elevator", "Shampoo", "Hair dryer", "Bed linens", "Air conditioning", "Freezer", "Coffee maker", "Dishwasher", "Oven", "Self check-in", "Refrigerator", "Dishes and silverware"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            54
["Wifi", "Kitchen", "TV", "Washer"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               50
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ..
["Private living room", "First aid kit", "Heating", "Wifi", "Smoking allowed", "Kitchen", "TV", "Essentials", "Washer", "Carbon monoxide alarm", "Iron", "Shampoo"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
["First aid kit", "Wifi", "Window AC unit", "Kitchen", "Essentials", "Stove", "Smart lock", "Hot water", "Iron", "Microwave", "Hangers", "Extra pillows and blankets", "Dining table", "Free washer \u2013 In unit", "Toaster", "Hot water kettle", "Carbon monoxide alarm", "Fire extinguisher", "Paid parking garage off premises", "HDTV", "Smoke alarm", "Radiant heating", "Hair dryer", "Drying rack for clothing", "Dishwasher", "Cleaning products", "Coffee maker: Nespresso", "Oven", "Self check-in", "Cooking basics", "Wine glasses", "Refrigerator", "Dishes and silverware"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
["Breakfast", "Wifi", "Kitchen", "Essentials", "Hot water", "Iron", "Paid parking off premises", "Microwave", "Hangers", "Portable fans", "Heating", "Private patio or balcony", "TV", "Washer", "Fire extinguisher", "Shampoo", "Long term stays allowed", "Hair dryer", "Coffee maker", "Dishwasher", "Cleaning products", "Oven", "Children\u2019s dinnerware", "Cooking basics", "Refrigerator", "Dishes and silverware"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
["Ethernet connection", "Wifi", "Central air conditioning", "Window AC unit", "Clothing storage: closet", "Kitchen", "Essentials", "Hot water", "Iron", "Luggage dropoff allowed", "Microwave", "Hangers", "Extra pillows and blankets", "Portable fans", "Dining table", "Free washer \u2013 In unit", "Pack \u2019n play/Travel crib", "Toaster", "Baking sheet", "Shower gel", "Hot water kettle", "Paid parking lot off premises", "High chair", "Indesit stainless steel oven", "Shampoo", "Wine glasses", "Radiant heating", "Long term stays allowed", "Body soap", "Hair dryer", "Bed linens", "Indesit induction stove", "50 inch HDTV with premium cable, standard cable", "Host greets you", "Freezer", "Laundromat nearby", "Drying rack for clothing", "Conditioner", "Window guards", "Dishwasher", "Private entrance", "Cleaning products", "Indesit refrigerator", "Coffee maker: Nespresso", "Paid parking garage on premises \u2013 1 space", "Children\u2019s dinnerware", "Cooking basics", "Room-darkening shades", "Dishes and silverware", "Crib", "Single level home"]     1
["Paid parking on premises", "Exercise equipment", "Smoke alarm", "Pool", "Exterior security cameras on property", "Wifi", "Smoking allowed", "Kitchen", "TV", "Washer", "Carbon monoxide alarm", "Fire extinguisher", "Air conditioning"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Name: count, Length: 15950, dtype: int64



has_availability

has_availability
yes    17082
no      1057
Name: count, dtype: int64



license

license
no     16321
yes     1818
Name: count, dtype: int64



instant_bookable

instant_bookable
f    10819
t     7320
Name: count, dtype: int64



neighbourhood_group

neighbourhood_group
Centro                7389
Salamanca             1224
Chamberí              1178
Tetuán                1131
Arganzuela             963
Carabanchel            699
Ciudad Lineal          674
Retiro                 674
Chamartín              609
Puente de Vallecas     560
Latina                 501
Moncloa                474
Usera                  421
San Blas               420
Hortaleza              342
Fuencarral             272
Villaverde             192
Moratalaz              137
Barajas                126
Villa de Vallecas       95
Vicálvaro               58
Name: count, dtype: int64



host_since

host_since
2020-11-30    241
2019-09-03    223
2021-12-30    214
2020-05-15    214
2023-06-07    178
             ...
2018-02-13      1
2018-11-06      1
2019-01-26      1
2015-09-26      1
2024-04-05      1
Name: count, Length: 3856, dtype: int64



first_review

first_review
2021-12-30    189
2020-05-15    151
2023-06-07     85
2022-07-28     85
2024-05-08     75
             ...
2019-01-06      1
2017-01-25      1
2019-01-07      1
2018-11-15      1
2015-03-07      1
Name: count, Length: 3591, dtype: int64



last_review

last_review
2024-12-08    862
2024-11-24    601
2024-12-01    555
2024-12-09    540
2024-11-25    377
             ...
2023-03-07      1
2019-01-27      1
2021-06-18      1
2021-10-07      1
2016-08-21      1
Name: count, Length: 2600, dtype: int64



bedrooms_disc

bedrooms_disc
01_Una             9915
02_Dos             3712
00_Estudio         2722
03_Tres            1287
04_Cuatro o mas     503
Name: count, dtype: int64



accommodates_disc

accommodates_disc
0-3     10775
4        4415
4-16     2949
Name: count, dtype: int64



beds_disc

beds_disc
1       9148
3       7351
3-19    1640
Name: count, dtype: int64



number_of_reviews_disc

number_of_reviews_disc
1-4        9166
5-71       5337
71-1136    3636
Name: count, dtype: int64

## 10. GESTIÓN DE NUMÉRICAS

### Estadísticos

In [37]:
num.describe().T

,count,mean,std,min,25%,50%,75%,max
index,18139.00,12982.65,7481.66,0.00,6508.50,12991.00,19470.50,25912.00
host_id,18139.00,247862242.73,203475000.33,7952.00,48380095.00,208980277.00,440993833.00,666295558.00
host_response_rate,18139.00,74.59,40.75,0.00,65.00,100.00,100.00,100.00
host_acceptance_rate,18139.00,84.68,24.51,0.00,82.00,97.00,100.00,100.00
host_listings_count,18139.00,49.89,134.00,1.00,1.00,3.00,23.00,3251.00
host_total_listings_count,18139.00,61.09,189.92,1.00,2.00,5.00,30.00,7970.00
latitude,18139.00,40.42,0.02,40.33,40.41,40.42,40.43,40.53
longitude,18139.00,-3.69,0.03,-3.83,-3.71,-3.70,-3.68,-3.55
accommodates,18139.00,3.16,1.89,1.00,2.00,3.00,4.00,16.00
bathrooms,18139.00,1.28,0.61,0.00,1.00,1.00,1.50,15.00
bedrooms,18139.00,1.30,0.98,0.00,1.00,1.00,2.00,12.00
beds,18139.00,1.85,1.25,0.00,1.00,1.00,2.00,19.00
price,18139.00,130.45,398.77,20.00,65.00,98.00,140.00,21347.00
minimum_nights,18139.00,7.98,27.34,1.00,1.00,2.00,4.00,1125.00
maximum_nights,18139.00,523.70,421.01,1.00,300.00,365.00,1125.00,1125.00
availability_30,18139.00,9.83,9.76,0.00,0.00,8.00,17.00,30.00
availability_60,18139.00,24.76,21.08,0.00,0.00,24.00,43.00,60.00
availability_90,18139.00,41.24,32.98,0.00,0.00,44.00,72.00,90.00
availability_365,18139.00,163.47,134.39,0.00,19.00,158.00,299.00,365.00
number_of_reviews,18139.00,47.69,87.78,0.00,1.00,11.00,54.00,1040.00
number_of_reviews_ltm,18139.00,14.63,21.90,0.00,0.00,4.00,22.00,302.00
number_of_reviews_l30d,18139.00,1.05,1.81,0.00,0.00,0.00,2.00,24.00
review_scores_rating,18139.00,3.72,1.91,0.00,4.00,4.68,4.89,5.00
review_scores_accuracy,18139.00,3.76,1.93,0.00,4.11,4.75,4.92,5.00
review_scores_cleanliness,18139.00,3.75,1.92,0.00,4.00,4.71,4.91,5.00
review_scores_checkin,18139.00,3.80,1.94,0.00,4.25,4.80,4.95,5.00
review_scores_communication,18139.00,3.81,1.95,0.00,4.21,4.83,4.97,5.00
review_scores_location,18139.00,3.80,1.93,0.00,4.19,4.79,4.95,5.00
review_scores_value,18139.00,3.65,1.88,0.00,4.00,4.58,4.80,5.00
calculated_host_listings_count,18139.00,34.76,79.85,1.00,1.00,3.00,17.00,343.00
calculated_host_listings_count_entire_homes,18139.00,31.07,78.56,0.00,0.00,1.00,11.00,343.00
calculated_host_listings_count_private_rooms,18139.00,3.54,16.52,0.00,0.00,0.00,1.00,175.00
calculated_host_listings_count_shared_rooms,18139.00,0.15,1.95,0.00,0.00,0.00,0.00,38.00
reviews_per_month,18139.00,1.50,1.88,0.00,0.06,0.77,2.33,25.76
precio_m2,18139.00,5317.01,1520.06,2070.00,4536.00,6170.00,6170.00,7846.00
m2,18139.00,57.68,18.44,40.00,50.00,50.00,70.00,150.00
pdi_sol,18139.00,2.78,2.45,0.00,0.84,2.03,4.11,14.53
pisos_rentables,18139.00,0.70,0.46,0.00,0.00,1.00,1.00,1.00

### 10.2. Nulos

#### 10.2.1. Identificación

In [38]:
num.isna().sum().sort_values(ascending = False)

index                                           0
review_scores_value                             0
number_of_reviews_l30d                          0
review_scores_rating                            0
review_scores_accuracy                          0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
calculated_host_listings_count                  0
host_id                                         0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
precio_m2                                       0
m2                                              0
pdi_sol                                         0
number_of_reviews_ltm                           0
number_of_reviews                               0
availability_365                                0
availability_90                                 0
host_response_rate                              0
host_acceptance_rate                            0
host_listings_count                             0
host_total_listings_count                       0
latitude                                        0
longitude                                       0
accommodates                                    0
bathrooms                                       0
bedrooms                                        0
beds                                            0
price                                           0
minimum_nights                                  0
maximum_nights                                  0
availability_30                                 0
availability_60                                 0
pisos_rentables                                 0
dtype: int64

## GUARDAR DATASETS TRAS CALIDAD DE DATOS

Guarda los avances en df, cat y num con un sufijo para poder guardar o recuperar avances del proyecto.

En formato pickle para no perder las modificaciones de metadatos.

### Definir los nombres de los archivos

In [39]:
ruta_trabajo = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'trabajo_resultado_calidad.pickle'
ruta_cat = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'cat_resultado_calidad.pickle'
ruta_num = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'num_resultado_calidad.pickle'

### Guardar los archivos

In [40]:
df.to_pickle(ruta_trabajo)
cat.to_pickle(ruta_cat)
num.to_pickle(ruta_num)